### ISSUE TITLE
Incompatible with Zabbix v3 with encryption

### ISSUE THREAD

**Issue by chihoko** [allenta/zabbix-template-for-varnish-cache#1]
I know this script is for Zabbix 2.4 but in case you plan to upgrade to v3, if you have encryption enabled on the server then the zabbix_sender needs to be configurable with the necessary parameters.

**Comment by fcollado** [comment]
You don't need to do anything with the UserParameter or the script, if zabbix_agentd is properly configured, zabbix_sender will use zabbix_agentd.conf file and will work like a charm.

**Comment by chihoko** [comment]
Are you sure? According to the [docs for zabbix sender](https://www.zabbix.com/documentation/3.0/manpages/zabbix_sender) when using --config option - "Only parameters Hostname, ServerActive and SourceIP are supported."

In my experience it doesn't work with the TLS parameters in the zabbix agent config file.

**Comment by muzetik** [comment]
Hi, I have the same issue, does not work with zabbix v3, will try deactivating encryption.

**Comment by fcollado** [comment]
Hi, 

I dind't test it using "RSA certificate-based encryption" but using "PSK-based encryption", `zabbix-varnish-cache.py` works whitouth problems.

This is my `zabbix_agentd.conf` file:

```
PidFile=/var/run/zabbix/zabbix_agentd.pid
LogFile=/var/log/zabbix/zabbix_agentd.log
LogFileSize=0
Server=somesite.somedomain.com
ServerActive=somesite.somedomain.com
ListenIP=0.0.0.0
Hostname=somename
TLSConnect=psk
TLSAccept=psk
TLSPSKIdentity=SomeID
TLSPSKFile=/etc/zabbix/zabbix_agentd.psk
UserParameter=varnish.discovery[*],/usr/local/bin/zabbix-varnish-cache.py -n '$1' discover $2
Include=/etc/zabbix/zabbix_agentd.d/
```

**Comment by carlosabalde** [comment]
Closed due to inactivity in the last 20 days. Please, reopen if required.
