### ISSUE TITLE
Zabbix 3.4 compatibility?

### ISSUE THREAD

**Issue by mfilocha** [allenta/zabbix-template-for-varnish-cache#10]
Are you aware of any problems arising from an upgrade to version 3.4.? I haven't investigated it yet, but no data is received by zabbix server since this upgrade. 
```
info from server: "processed: 0; failed: 229; total: 229; seconds spent: 0.002343"
sent: 229; skipped: 0; total: 229
```

**Comment by carlosabalde** [comment]
No known problems. Sorry!
