### ISSUE TITLE
Wrong template

### ISSUE THREAD

**Issue by wizhippo** [allenta/zabbix-template-for-varnish-cache#14]
When importing it fails as the wrong template name is used.  Not sure also by docs which of the template should be imported.

https://github.com/allenta/zabbix-template-for-varnish-cache/blob/f1f7fffe0e0c4e43629e8b3e0eed92bdb00c37d1/template-app-varnish-cache.xml#L4613

Template App Varnish Cache

**Comment by carlosabalde** [comment]
You're right. That's a typo. It's fixed now in master & 6.0 branches. Thanks!

**Comment by carlosabalde** [comment]
Selecting between the passive and active templates depends on your environment and how you plan to set up your agents.
