### ISSUE TITLE
Command failed with error code 106 Invalid flags -j [failed: 90]

### ISSUE THREAD

**Issue by Cescolinguisticservices** [allenta/zabbix-template-for-varnish-cache#15]
/usr/local/bin/zabbix-varnish-cache.py -i 'amstelveen' send -c /etc/zabbix/zabbix_agentd.conf -z <zabbix_hostname> -s <zabbix_hostname>

Command failed with error code 106
Invalid flags -j

- varnish.stat["","MAIN.fetch_head"] 1538937376 0
- varnish.stat["","MAIN.sess_dropped"] 1538937376 0
- varnish.stat["","MAIN.s_pipe_hdrbytes"] 1538937376 0
- varnish.stat["","MAIN.fetch_bad"] 1538937376 0
- varnish.stat["","MAIN.cache_miss"] 1538937376 2
- varnish.stat["","MGT.uptime"] 1538937376 349064
- varnish.stat["","MAIN.fetch_no_thread"] 1538937376 0
- varnish.stat["","VBE.default.req"] 1538937376 2
- varnish.stat["","MAIN.n_objecthead"] 1538937376 0
- varnish.stat["","MAIN.s_req_bodybytes"] 1538937376 0
- varnish.stat["","MAIN.threads_destroyed"] 1538937376 0
- varnish.stat["","MAIN.thread_queue_len"] 1538937376 0
- varnish.stat["","MAIN.fetch_none"] 1538937376 0
- varnish.stat["","MAIN.fetch_length"] 1538937376 0
- varnish.stat["","MAIN.fetch_chunked"] 1538937376 2
- varnish.stat["","MAIN.s_pass"] 1538937376 0
- varnish.stat["","MAIN.n_expired"] 1538937376 2
- varnish.stat["","VBE.default.beresp_hdrbytes"] 1538937376 2934
- varnish.stat["","MAIN.esi_errors"] 1538937376 0
- varnish.stat["","MAIN.threads_limited"] 1538937376 0
- varnish.stat["","MAIN.n_gzip"] 1538937376 0
- varnish.stat["","MAIN.backend_unhealthy"] 1538937376 0
- varnish.stat["","MAIN.sess_closed_err"] 1538937376 0
- varnish.stat["","MAIN.fetch_304"] 1538937376 0
- varnish.stat["","MAIN.backend_reuse"] 1538937376 0
- varnish.stat["","MAIN.sess_closed"] 1538937376 2
- varnish.stat["","MAIN.cache_hit"] 1538937376 0
- varnish.stat["","MAIN.bans"] 1538937376 1
- varnish.stat["","MAIN.client_req_400"] 1538937376 0
- varnish.stat["","MAIN.threads_failed"] 1538937376 0
- varnish.stat["","MAIN.s_resp_hdrbytes"] 1538937376 1466
- varnish.stat["","STG.SMA.Transient.g_bytes"] 1538937376 0
- varnish.stat["","VBE.default.conn"] 1538937376 0
- varnish.stat["","MAIN.busy_sleep"] 1538937376 0
- varnish.stat["","VBE.default.pipe_in"] 1538937376 0
- varnish.stat["","MAIN.client_req_417"] 1538937376 0
- varnish.stat["","MAIN.threads"] 1538937376 200
- varnish.stat["","MAIN.n_backend"] 1538937376 1
- varnish.stat["","MAIN.busy_wakeup"] 1538937376 0
- varnish.stat["","STG.SMA.Transient.c_fail"] 1538937376 0
- varnish.stat["","MAIN.s_pipe"] 1538937376 0
- varnish.stat["","MAIN.sess_fail"] 1538937376 0
- varnish.stat["","MAIN.uptime"] 1538937376 349065
- varnish.stat["","MAIN.bans_lurker_obj_killed"] 1538937376 0
- varnish.stat["","MAIN.fetch_failed"] 1538937376 0
- varnish.stat["","MAIN.n_purges"] 1538937376 0
- varnish.stat["","MAIN.s_pipe_in"] 1538937376 0
- varnish.stat["","MAIN.s_fetch"] 1538937376 2
- varnish.stat["","MAIN.fetch_204"] 1538937376 0
- varnish.stat["","MAIN.bans_obj_killed"] 1538937376 0
- varnish.stat["","MAIN.s_synth"] 1538937376 0
- varnish.stat["","MAIN.esi_warnings"] 1538937376 0
- varnish.stat["","MAIN.n_objectcore"] 1538937376 0
- varnish.stat["","MAIN.backend_fail"] 1538937376 0
- varnish.stat["","STG.SMF.s0.g_space"] 1538937376 1073741824
- varnish.stat["","MAIN.busy_killed"] 1538937376 0
- varnish.stat["","MAIN.client_req"] 1538937376 2
- varnish.stat["","STG.SMF.s0.c_fail"] 1538937376 0
- varnish.stat["","VBE.default.bereq_hdrbytes"] 1538937376 964
- varnish.stat["","VBE.default.happy"] 1538937376 0
- varnish.stat["","MAIN.sess_queued"] 1538937376 0
- varnish.stat["","MAIN.backend_conn"] 1538937376 2
- varnish.stat["","STG.SMA.Transient.g_space"] 1538937376 0
- varnish.stat["","VBE.default.bereq_bodybytes"] 1538937376 0
- varnish.stat["","MAIN.s_sess"] 1538937376 2
- varnish.stat["","MAIN.s_pipe_out"] 1538937376 0
- varnish.stat["","MAIN.sess_readahead"] 1538937376 0
- varnish.stat["","MAIN.cache_hit_grace"] 1538937376 0
- varnish.stat["","MAIN.backend_busy"] 1538937376 0
- varnish.stat["","MAIN.n_lru_nuked"] 1538937376 0
- varnish.stat["","MAIN.sess_conn"] 1538937376 2
- varnish.stat["","MAIN.losthdr"] 1538937376 0
- varnish.stat["","MAIN.fetch_1xx"] 1538937376 0
- varnish.stat["","MAIN.cache_hitpass"] 1538937376 0
- varnish.stat["","MAIN.backend_req"] 1538937376 2
- varnish.stat["","VBE.default.pipe_hdrbytes"] 1538937376 0
- varnish.stat["","MAIN.fetch_eof"] 1538937376 0
- varnish.stat["","MAIN.n_lru_limited"] 1538937376 0
- varnish.stat["","MAIN.n_obj_purged"] 1538937376 0
- varnish.stat["","MAIN.backend_retry"] 1538937376 0
- varnish.stat["","MAIN.s_resp_bodybytes"] 1538937376 25533
- varnish.stat["","STG.SMF.s0.g_bytes"] 1538937376 0
- varnish.stat["","MAIN.s_req_hdrbytes"] 1538937376 970
- varnish.stat["","MAIN.backend_recycle"] 1538937376 2
- varnish.stat["","MAIN.n_object"] 1538937376 0
- varnish.stat["","MAIN.threads_created"] 1538937376 200
- varnish.stat["","MAIN.n_gunzip"] 1538937376 2
- varnish.stat["","MAIN.sess_drop"] 1538937376 0
- varnish.stat["","VBE.default.beresp_bodybytes"] 1538937376 25533
- varnish.stat["","VBE.default.pipe_out"] 1538937376 0
info from server: "processed: 0; failed: 90; total: 90; seconds spent: 0.000633"
sent: 90; skipped: 0; total: 90

**Comment by carlosabalde** [comment]
Wrong branch.
