### ISSUE TITLE
Varnish raw log is not running | Varnish NCSA log is not running

### ISSUE THREAD

**Issue by kaustuva** [allenta/zabbix-template-for-varnish-cache#16]
Hello Support,

I have followed installation guide. I setup following cron job on zabbix client/Varnish server.

* * * * * /usr/local/bin/zabbix-varnish-cache.py -i <varnish_host> send -c /etc/zabbix/zabbix_agentd.conf -z <zabbix server hostname> -s <zabbix server hostname> > /dev/null 2>&1

But On Zabbix server, i can see varnish raw log is not running & Varnish NCSA log is not running. please see here http://prntscr.com/l3i5ek

When i run the python script manually at Varnish server/Zabbix client end, i got these errors
Command failed with error code 106
Invalid flags -j
- varnish.stat["amstelveen","MAIN.fetch_head"] 1538937297 0
- varnish.stat["amstelveen","MAIN.sess_dropped"] 1538937297 0
- varnish.stat["amstelveen","MAIN.s_pipe_hdrbytes"] 1538937297 0
- varnish.stat["amstelveen","MAIN.fetch_bad"] 1538937297 0
- varnish.stat["amstelveen","MAIN.cache_miss"] 1538937297 2
- varnish.stat["amstelveen","MGT.uptime"] 1538937297 348985
..
.....
.......
- varnish.stat["amstelveen","VBE.default.beresp_bodybytes"] 1538937857 25533
- varnish.stat["amstelveen","VBE.default.pipe_out"] 1538937857 0
info from server: "processed: 0; failed: 90; total: 90; seconds spent: 0.000758"
sent: 90; skipped: 0; total: 90

Please assist me.

**Comment by carlosabalde** [comment]
It looks like you are using the wrong branch. For example, if using Varnish Cache 4.1.10 you should use branch `4.1`.

**Comment by carlosabalde** [comment]
On the other hand, about the raw & NCSA log alerts. Probably you get those alerts because those services are not running. They are not mandatory and usually they are not enabled.

**Comment by kaustuva** [comment]
thank you very much @carlosabalde for your quick response. I have updated script to 4.1.10 and the first issue is resolved. But second issue is still there as follows after running the script from Varnish server/Zabbix client end.

info from server: "processed: 0; failed: 91; total: 91; seconds spent: 0.001266"

May i need to enable and start varnishncsa, varnishadm services?

**Comment by carlosabalde** [comment]
Is the second issue the raw & NCSA alerts? If so, that's not an issue. If you don't plan to run those services (which is the most common scenario), is normal you get the alert. Simply disable those triggers in the template.

**Comment by carlosabalde** [comment]
And about the failed items when submitting values, that's probably related with some problem with Zabbix discovery, perhaps some problem in the configuration of the user parameters, etc.

**Comment by kaustuva** [comment]
When i run this script manually from zabbix client/varnish server, i got this error at the end.
#/usr/local/bin/zabbix-varnish-cache.py -i 'amstelveen' send -c /etc/zabbix/zabbix_agentd.conf -s <zabbix.server>-z <zabbix.server>

.........
.....
- varnish.stat["amstelveen","VBE.default.beresp_bodybytes"] 1539004895 25533
- varnish.stat["amstelveen","VBE.default.healthy"] 1539004895 1
- varnish.stat["amstelveen","VBE.default.pipe_out"] 1539004895 0
info from server: "processed: 0; failed: 91; total: 91; seconds spent: 0.000885"
sent: 91; skipped: 0; total: 91

Please see the front end status of zabbix. http://prntscr.com/l3kuyp

**Comment by carlosabalde** [comment]
As I said, that's probably related with some problem with Zabbix discovery, perhaps some problem in the configuration of the user parameters, etc. You need to review your configuration and check everything carefully.
