### ISSUE TITLE
no data at Zabbix-frontend

### ISSUE THREAD

**Issue by kaustuva** [allenta/zabbix-template-for-varnish-cache#18]
Sorry i couldn't make it work so far.
My Zabbix server version is 3.4.7, varnish version is 4.1 and i am using correct 4.1 branch files. 
Varnish discovery is enabled. http://prntscr.com/l5gak1
I have added "UserParameter=varnish.discovery[*],/usr/local/bin/zabbix-varnish-cache.py -i '$1' discover $2" in /etc/zabbix/zabbix_agentd.conf of varnish server
But when i run /usr/local/bin/zabbix-varnish-cache.py python script, it shows me the following error.
....
....
- varnish.stat["amstelveen","MAIN.sess_drop"] 1539378016 0
- varnish.stat["amstelveen","VBE.default.beresp_bodybytes"] 1539378016 38235
- varnish.stat["amstelveen","VBE.default.healthy"] 1539378016 1
- varnish.stat["amstelveen","VBE.default.pipe_out"] 1539378016 0
zabbix_sender [1385]: DEBUG: answer [{"response":"success","info":"processed: 0; failed: 91; total: 91; seconds spent: 0.000673"}]
info from server: "processed: 0; failed: 91; total: 91; seconds spent: 0.000673"
sent: 91; skipped: 0; total: 91

Please help me.

**Comment by kaustuva** [comment]
I am receiving mail as like follows

Host: <Varnish_hostname>
Item: Varnish Cache[] - Cache hit ratio
Key: varnish["","cache_hit_ratio"]
State: Not supported

**Comment by carlosabalde** [comment]
You're probably using the wrong options when running the  `zabbix-varnish-cache.py` script. This is the example zabbix crontab entry in the docs:

```
* * * * * /usr/local/bin/zabbix-varnish-cache.py -i '' send -c /etc/zabbix/zabbix_agentd.conf -s dev > /dev/null 2>&1
```
Beware usually you want to include `-i ''`, usually you don't need to use the `-z` option when using `-c` and, very important, value in `-s` should match the hostname as defined in Zabbix.

**Comment by kaustuva** [comment]
@carlosabalde, thank you very much. It works for me.
/usr/local/bin/zabbix-varnish-cache.py -i '' send -c /etc/zabbix/zabbix_agentd.conf -s (hostname)

I can see some data on frontend. Please help me to resolve this issue. http://prntscr.com/l5prmr
Cache_hit_ratio is an important parameters to monitor. Please assist me.

**Comment by carlosabalde** [comment]
The hit ratio is a calculated item. You need some traffic in order to make it work.

**Comment by kaustuva** [comment]
thank you. I am having similar issues still. Please see these 2 screenshots.
you can see items are correctly passed and processed at server end too. http://prntscr.com/l6gqjk
But still no data at zabbix front end. http://prntscr.com/l6gr42
Please assist me.
