### ISSUE TITLE
Question for send option

### ISSUE THREAD

**Issue by iamkristian** [allenta/zabbix-template-for-varnish-cache#2]
Sorry for troubling you - I've got a question for the send option.

[zabbix-varnish-cache.py line 115](https://github.com/allenta/zabbix-template-for-varnish-cache/blob/master/zabbix-varnish-cache.py#L115)

``` python
row = '- varnish.stat["%(key)s"] %(tst)d %(value)d\n' % {
```

What is the idea with the `-` infront of `varnish.stat`? To add a delimiter for a `cut` option?

Thanks,
Kristian

**Comment by carlosabalde** [comment]
Hi,

That's the format required by Zabbix sender. The `-` value will be replaced by the host name in the configuration. Please, check description of the `-i` and `-T` options in [the man page](https://www.zabbix.com/documentation/2.4/manpages/zabbix_sender):

> [...] Each line of file contains whitespace delimited: &lt;hostname&gt; &lt;key&gt; &lt;value&gt;. Specify - in <hostname> to use hostname from configuration file or --host argument. All entries are sent in a sequential order top-down.

**Comment by iamkristian** [comment]
Thanks a lot! That really helped :-)
