### ISSUE TITLE
no data 

### ISSUE THREAD

**Issue by kaustuva** [allenta/zabbix-template-for-varnish-cache#25]
Sorry to fork another ticket. I am having similar issues still. Please see these 2 screenshots.
you can see items are correctly passed and processed at server end too. http://prntscr.com/l6gqjk
But still no data at zabbix front end. http://prntscr.com/l6gr42
Please assist me.

**Comment by carlosabalde** [comment]
I'm sorry but I'm afraid what you're reporting is not an issue with the template. You might be interested in joining our next Zabbix training held in Madrid: https://allenta.com/es/formacion-profesional-y-certificacion-zabbix.
