### ISSUE TITLE
Running discovery backends returns empty json

### ISSUE THREAD

**Issue by mbechc** [allenta/zabbix-template-for-varnish-cache#3]
Running the discovery manually produces this output

[root@e ~]# /usr/local/bin/zabbix-varnish-cache.py -n e.varnish.web.tv2net.dk discover backends
{
  "data": []
}

It looks like the regex in discovery->backends doesn't like our backend names ?!

Name after "service varnish restart"
"VBE.boot.web17.beresp_bodybytes":

Name after "service varnish reload"
 "VBE.reload_2016-03-15T11:08:18.web17.bereq_bodybytes":

**Comment by carlosabalde** [comment]
Regexps used when discovering backends and storages has just been simplified in 3c023aee119963361f6319e48d8e5141eee62895. This new version of  `zabbix-varnish-cache.py` should discover your backends. Some extra work would be required to avoid changed in the names of the items.

**Comment by carlosabalde** [comment]
... and the pending extra work is included in c2623b0de79a391890dbedf8ffc8fa574b6a6336. Please, let us know if this fixed your problem.

**Comment by mbechc** [comment]
Everything seems in order. Thank you so much
