### ISSUE TITLE
item value failed

### ISSUE THREAD

**Issue by redbox-cdn** [allenta/zabbix-template-for-varnish-cache#4]
Hi thank you for the special script, 

I have one question about value of the item .

zabbix 2.x
Varnish 4.1.x

If I execute this command , some item is failed.

/usr/local/sbin/varnish_status.py send  -c /etc/zabbix_agent.conf -z ZabbixServerIP -s Hostname

info from server: "processed: 73; failed: 26; total: 99; seconds spent: 0.000917"
sent: 99; skipped: 0; total: 99

How can I checked what failed items?

I already set the templates.xml in the zabbix server.

best regards

**Comment by carlosabalde** [comment]
Hi @redbox2000,

I've consulted with our local Zabbix ninja at Allenta at he suggests increasing Zabbix Sender log level to debug and check logs. Anyway, those 26 failed items are probably items (i.e. storages and backends) not yet discovered by the discovery script.
