### ISSUE TITLE
zabbix-varnish-cache.py  Command failed with error code 102  JSON unimplemented

### ISSUE THREAD

**Issue by Johanhen** [allenta/zabbix-template-for-varnish-cache#40]
Hello all, When i run the zabbix-varnish-cache.py file i get the following error. After the error all looks fine but zabbix complains about the output not beeing JSON.

root@varnish-staging:/usr/local/bin # ./zabbix-varnish-cache.py -i '' send -c /usr/local/etc/zabbix/zabbix_agentd.conf
Command failed with error code 102
JSON unimplemented

- varnish.stat["","MAIN.fetch_head"] 1542121939 0
- varnish.stat["","VBE.webserver10.fail_enetunreach"] 1542121939 0
- varnish.stat["","MAIN.sess_dropped"] 1542121939 0
- varnish.stat["","VBE.shared10.unhealthy"] 1542121939 0
- varnish.stat["","VBE.flib01.beresp_hdrbytes"] 1542121939 0
- varnish.stat["","VBE.shared12.pipe_in"] 1542121939 0
........

- varnish.stat["","VBE.bekijk04.fail_eaddrnotavail"] 1542122165 0
- varnish.stat["","VBE.webserver09.unhealthy"] 1542122165 0
info from server: "processed: 0; failed: 250; total: 250; seconds spent: 0.003921"
info from server: "processed: 0; failed: 2; total: 2; seconds spent: 0.000093"
sent: 252; skipped: 0; total: 252

This is on FreeBSD 11.2 
Thanks for your time.

regards
Johan

**Comment by carlosabalde** [comment]
You should execute the discovery script manually as Zabbix user and check output.

**Comment by Johanhen** [comment]
Ah, i did the following: crontab -e -u zabbix
* * * * * /usr/local/bin/zabbix-varnish-cache.py -i '' send -c /usr/local/etc/zabbix/zabbix_agentd.conf -s dev > /tmp/zabbixoutput

And then the following is put to that file:

- varnish.stat["","MAIN.fetch_head"] 1542124200 0
- varnish.stat["","VBE.webserver10.fail_enetunreach"] 1542124200 0
- varnish.stat["","MAIN.sess_dropped"] 1542124200 0
- varnish.stat["","VBE.shared10.unhealthy"] 1542124200 0
.....
- varnish.stat["","VBE.shared10.busy"] 1542124200 0
- varnish.stat["","VBE.shared11.pipe_in"] 1542124200 0
- varnish.stat["","VBE.bekijk04.fail_eaddrnotavail"] 1542124200 0
- varnish.stat["","VBE.webserver09.unhealthy"] 1542124200 0

so that looks good, but zabbix still complains with the following
![schermafbeelding 2018-11-13 om 16 51 49](https://user-images.githubusercontent.com/478828/48425143-7c1fba00-e764-11e8-8a5f-554fea82e223.png)

**Comment by carlosabalde** [comment]
That's not the output of the discovery. Run the discovery as run by Zabbix Agent and you'll finde the problem.

**Comment by Johanhen** [comment]
Sorry if i am waisting your time... 
It runs partially now. I used -s dev which had to be -s varnish.mydomain.com
I need to read better!

The items discovery rule works.
if i run the following as user zabbix i get this output.
}$ sudo /usr/local/bin/zabbix-varnish-cache.py -i '' discover items
{
  "data": [
    {
      "{#LOCATION_ID}": "",
      "{#LOCATION}": ""
    }
  ]
}$

I now have a lot of items in my zabbix dashboard and the i is gone after the items discovery rule, but the backend and storage discovery still give me the value should ba a JSON object
if i run the following i get this :
$ sudo /usr/local/bin/zabbix-varnish-cache.py -i '' discover backends
Command failed with error code 102
JSON unimplemented

{
  "data": [
    {
      "{#LOCATION_ID}": "",
      "{#LOCATION}": "",
      "{#SUBJECT_ID}": "webserver10",
      "{#SUBJECT}": "webserver10"
    },
And so for all the other backends.
for the storages discovery rule the same 
$ sudo /usr/local/bin/zabbix-varnish-cache.py -i '' discover storages
Command failed with error code 102
JSON unimplemented

{
  "data": [
    {
      "{#LOCATION_ID}": "",
      "{#LOCATION}": "",
      "{#SUBJECT_ID}": "SMA.s0",
      "{#SUBJECT}": "SMA.s0"
    },
    {
      "{#LOCATION_ID}": "",
      "{#LOCATION}": "",
      "{#SUBJECT_ID}": "SMA.Transient",
      "{#SUBJECT}": "SMA.Transient"
    }
  ]
}$
So it looks like it gives me json output but i think it trips over the first error message which i do not get for items?

in the debug log on the client i see this:
 67179:20181113:205312.546 EXECUTE_STR() command:'/usr/local/bin/zabbix-varnish-cache.py -i '' discover storages' len:350 cmd_result:'Command failed with ' 
67179:20181113:205312.546 Sending back [Command failed with error code 102
JSON unimplemented

{
  "data": [
    {
      "{#LOCATION_ID}": "",
      "{#LOCATION}": "",
      "{#SUBJECT_ID}": "SMA.s0",
      "{#SUBJECT}": "SMA.s0"
    },
    {
      "{#LOCATION_ID}": "",
      "{#LOCATION}": "",
      "{#SUBJECT_ID}": "SMA.Transient",
      "{#SUBJECT}": "SMA.Transient"
    }
  ]
}]

Thanks again for your time.

**Comment by carlosabalde** [comment]
In addition to the `-s` option, the problem you are experiencing is definitely related with those error messages when executing the discovery script. What Varnish Cache version are you using? Are you using the right branch for that version?

**Comment by Johanhen** [comment]
Starting varnishd.
Debug: Version: varnish-6.0.1 revision NOGIT
Debug: Platform: FreeBSD,11.2-RELEASE-p4,amd64,-junix,-smalloc,-sdefault,-hcritbit
Debug: Child (68558) Started

So sorry, i used the wrong branch! i assumed the master would be ok for all., and did not really looked at the branches.
I downloaded the 6.0 branch script and no problems anymore with the discover rules.

Thank you very much for your time!.

**Comment by carlosabalde** [comment]
You're welcome. You should use both the script and the template in the `6.0` branch. Thanks!
