### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by forum77alive** [allenta/zabbix-template-for-varnish-cache#45]
Help, please
root@debian:/tmp/zabbix-template-for-varnish-cache# jinja2 \
> -D version={4.0,4.2,4.4} \
> [-D name='Varnish Cache'] \
> [-D lite=0] \
> --strict -o template.xml template-app-varnish-cache.j2
Traceback (most recent call last):
  File "/usr/local/bin/jinja2", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jinja2cli/cli.py", line 424, in main
    sys.exit(cli(opts, args))
  File "/usr/local/lib/python2.7/dist-packages/jinja2cli/cli.py", line 241, in cli
    template_path, data = args
ValueError: too many values to unpack

**Comment by davidfb** [comment]
Hi @forum77alive,

I'm afraid you are not properly executing the command. For the _version_ parameter you should choose one of the three available options (that's what the brackets mean): _4.0_, _4.2_, or _4.4_. As for the _name_ and _lite_ parameters, they are optional (that's what the square brackets mean) so you can include them or not, but always without the brackets (they are just used in documentation to make explicit that those are optional paremeters).

So, for example, if you wanted to generate a template for Zabbix 4.4 and give it a name different than the default one, you should execute it like this:

`jinja2 -D version=4.4 -D name='VCP' --strict -o template.xml template-app-varnish-cache.j2`

Or if the default name (Varnish Cache) is OK for you:

`jinja2 -D version=4.4 --strict -o template.xml template-app-varnish-cache.j2`

This should get you on track :)

**Comment by forum77alive** [comment]
Thank you!
