### ISSUE TITLE
Could not get hold of varnishd, is it running?

### ISSUE THREAD

**Issue by forum77alive** [allenta/zabbix-template-for-varnish-cache#46]
Sorry, but i can't started script

root@debian:~# sudo -u zabbix sudo /usr/local/bin/zabbix-varnish-cache.py --varnish-instances 127.0.0.1 stats
.....
Could not get hold of varnishd, is it running?
.....
Could not get hold of varnishd, is it running?

I added string to sudoers
zabbix  ALL= (ALL) NOPASSWD: /usr/local/bin/zabbix-varnish-cache.py

and

chmod +x /usr/local/bin/zabbix-varnish-cache.py,
sudo usermod -a --groups varnish zabbix,
sudo usermod -a --groups varnish root

and not working. What I need doing else?
Thanks

**Comment by davidfb** [comment]
Hi! _--varnish-instances_ (or it's shortcut _-i_) establishes the name of the Varnish Cache instance you want the script to talk to. It should match the value given through the _-n_ parameter to _varnishd_. If no special name was given to the _varnishd_ process, you can simply leave it blank:
`sudo /usr/local/bin/zabbix-varnish-cache.py -i '' stats`

Does this explanation clear up things a little bit?

**Comment by forum77alive** [comment]
Yes, you right. Thank you very much
