### ISSUE TITLE
Skiping acces zabbix-varnish-cache.py to "_.secret" 

### ISSUE THREAD

**Issue by myhellone** [allenta/zabbix-template-for-varnish-cache#49]
For security reason I don't have acces to file /var/lib/varnish/lab1//_.secret 
There is a way to skip this file in zabbix-varnish-cache.py ?

`zabbix@lab /var/lib/zabbix/externalscripts $ ./zabbix-varnish-cache.py -i '' discover backends`
 `Cannot open "/var/lib/varnish/lab1//_.secret": Permission denied`

**Comment by carlosabalde** [comment]
As explained in README.rst, the recommendation is to grant sudo permissions to the `zabbix` user to execute the script. If not possible, at least you should add the `zabbix` user to the `varnish` group. Hope it helps.
