### ISSUE TITLE
Varnish Cache Template problem?

### ISSUE THREAD

**Issue by ekkljs** [allenta/zabbix-template-for-varnish-cache#5]
Running Zabbix 2.4.8, Varnish 4.0.3 and trying to monitor Varnish cache.
Checked cron log, zabbix agent log on the client and it seems everything is setup correctly but I don't see any data collected. On the server side every item related with Varnish is enabled except Varnish- Cache hit ratio.

**Comment by carlosabalde** [comment]
Some ideas:
- Are discoverable items (i.e. backends and storages) properly discovered?
- Are you including the right value in the `-s` option when sending stats through Zabbix Sender?
- Have you tried manual execution of the cron job and checked no errors show up in the output? Same thing using the Zabbix Agent user?
- Have you enabled debug level in Zabbix Agent and Server when looking for errors in log files?

**Comment by ekkljs** [comment]
Thanks for suggestion! Following is the log from Zabbix Agent on client. 

23198:20160603:152012.094 listener #2 [processing request]
 23198:20160603:152012.095 Requested [varnish.discovery[,backends]]
 23198:20160603:152012.095 In zbx_popen() command:'/usr/local/bin/zabbix-varnish-cache.py -n '' discover backends'
 23198:20160603:152012.095 End of zbx_popen():7
 24088:20160603:152012.096 zbx_popen(): executing script
 23198:20160603:152012.113 In zbx_waitpid()
 23198:20160603:152012.114 zbx_waitpid() exited, status:2
 23198:20160603:152012.114 End of zbx_waitpid():24088
 23198:20160603:152012.114 EXECUTE_STR() command:'/usr/local/bin/zabbix-varnish-cache.py -n '' discover backends' len:1247 cmd_result:'/usr/local/bin/zabbi'
 23198:20160603:152012.114 Sending back [/usr/local/bin/zabbix-varnish-cache.py: line 1: 癤?!/usr/bin/env: No such file or directory
/usr/local/bin/zabbix-varnish-cache.py: line 3: 
: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 8: 
:url: https://github.com/allenta/zabbix-template-for-varnish-cache
:copyright: (c) 2015 by Allenta Consulting S.L. info@allenta.com.
:license: BSD, see LICENSE.txt for more details.

: No such file or directory
/usr/local/bin/zabbix-varnish-cache.py: line 9: 
: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 10: from: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 11: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 12: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 13: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 14: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 15: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 16: from: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 17: 
: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 18: syntax error near unexpected token `('
/usr/local/bin/zabbix-varnish-cache.py: line 18:`ITEMS = re.compile(
']
 23198:20160603:152012.114 listener #2 [waiting for connection]
 23200:20160603:152012.692 In send_buffer() host:'10.0.0.90' port:10051 values:0/100
 23200:20160603:152012.692 End of send_buffer():SUCCEED
 23200:20160603:152012.692 active checks #1 [idle 1 sec]
 23196:20160603:152012.915 collector [processing data]
 23196:20160603:152012.915 In update_cpustats()
 23196:20160603:152012.915 End of update_cpustats()
 23196:20160603:152012.915 collector [idle 1 sec]
 23199:20160603:152013.109 listener #3 [processing request]
 23199:20160603:152013.110 Requested [varnish.discovery[,storages]]
 23199:20160603:152013.110 In zbx_popen() command:'/usr/local/bin/zabbix-varnish-cache.py -n '' discover storages'
 23199:20160603:152013.110 End of zbx_popen():7
 24105:20160603:152013.110 zbx_popen(): executing script
 23199:20160603:152013.128 In zbx_waitpid()
 23199:20160603:152013.129 zbx_waitpid() exited, status:2
 23199:20160603:152013.129 End of zbx_waitpid():24105
 23199:20160603:152013.129 EXECUTE_STR() command:'/usr/local/bin/zabbix-varnish-cache.py -n '' discover storages' len:1247 cmd_result:'/usr/local/bin/zabbi'
 23199:20160603:152013.129 Sending back [/usr/local/bin/zabbix-varnish-cache.py: line 1: 癤?!/usr/bin/env: No such file or directory
/usr/local/bin/zabbix-varnish-cache.py: line 3: 
: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 8: 
:url: https://github.com/allenta/zabbix-template-for-varnish-cache
:copyright: (c) 2015 by Allenta Consulting S.L. info@allenta.com.
:license: BSD, see LICENSE.txt for more details.

: No such file or directory
/usr/local/bin/zabbix-varnish-cache.py: line 9: 
: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 10: from: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 11: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 12: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 13: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 14: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 15: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 16: from: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 17: 
: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 18: syntax error near unexpected token `('
/usr/local/bin/zabbix-varnish-cache.py: line 18:`ITEMS = re.compile(
']
 23199:20160603:152013.129 listener #3 [waiting for connection]
 23198:20160603:152013.217 listener #2 [processing request]
 23198:20160603:152013.217 Requested [system.uname]
 23198:20160603:152013.217 Sending back [Linux proxy.jjd 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 00:57:44 UTC 2016 x86_64]
 23198:20160603:152013.217 listener #2 [waiting for connection]
 23200:20160603:152013.693 In send_buffer() host:'10.0.0.90' port:10051 values:0/100
 23200:20160603:152013.693 End of send_buffer():SUCCEED
 23200:20160603:152013.693 active checks #1 [idle 1 sec]
 23196:20160603:152013.915 collector [processing data]
 23196:20160603:152013.915 In update_cpustats()
 23196:20160603:152013.916 End of update_cpustats()
 23196:20160603:152013.916 collector [idle 1 sec]
 23200:20160603:152014.693 In send_buffer() host:'10.0.0.90' port:10051 values:0/100
 23200:20160603:152014.693 End of send_buffer():SUCCEED
 23200:20160603:152014.693 active checks #1 [idle 1 sec]
 23196:20160603:152014.916 collector [processing data]
 23196:20160603:152014.916 In update_cpustats()
 23196:20160603:152014.916 End of update_cpustats()
 23196:20160603:152014.916 collector [idle 1 sec]
 23198:20160603:152015.301 listener #2 [processing request]
 23198:20160603:152015.301 Requested [system.uname]

This is the log from Zabbix Server.

10254:20160603:160008.582 In substitute_key_macros() data:'IF-MIB::ifAdminStatus.4'
 10258:20160603:160008.582 In filter_evaluate_and_or()
 10255:20160603:160008.582 get value from agent result: '/usr/local/bin/zabbix-varnish-cache.py: line 1: 癤?!/usr/bin/env: No such file or directory
/usr/local/bin/zabbix-varnish-cache.py: line 3: 
: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 8: 
:url: https://github.com/allenta/zabbix-template-for-varnish-cache
:copyright: (c) 2015 by Allenta Consulting S.L. info@allenta.com.
:license: BSD, see LICENSE.txt for more details.

: No such file or directory
/usr/local/bin/zabbix-varnish-cache.py: line 9: 
: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 10: from: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 11: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 12: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 13: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 14: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 15: import: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 16: from: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 17: 
: command not found
/usr/local/bin/zabbix-varnish-cache.py: line 18: syntax error near unexpected token `('
/usr/local/bin/zabbix-varnish-cache.py: line 18:`ITEMS = re.compile(
''
 10256:20160603:160008.582 query [txnlev:0] [select id.itemid,id.key_,id.lastcheck,id.ts_delete,i.name,i.key_,i.type,i.value_type,i.data_type,i.delay,i.delay_flex,i.history,i.trends,i.trapper_hosts,i.units,i.multiplier,i.delta,i.formula,i.logtimefmt,i.valuemapid,i.params,i.ipmi_sensor,i.snmp_community,i.snmp_oid,i.port,i.snmpv3_securityname,i.snmpv3_securitylevel,i.snmpv3_authprotocol,i.snmpv3_authpassphrase,i.snmpv3_privprotocol,i.snmpv3_privpassphrase,i.authtype,i.username,i.password,i.publickey,i.privatekey,i.description,i.interfaceid,i.snmpv3_contextname from item_discovery id join items i on id.itemid=i.itemid where id.parent_itemid=24160]
 10254:20160603:160008.583 End of substitute_key_macros():SUCCEED data:'IF-MIB::ifAdminStatus.4'
 10255:20160603:160008.583 End of get_value_agent():SUCCEED
 10258:20160603:160008.583 End of filter_evaluate_and_or():SUCCEED
 10256:20160603:160008.583 End of lld_items_get()
 10255:20160603:160008.583 End of get_value():SUCCEED
 10258:20160603:160008.583 In filter_evaluate_and_or()
 10254:20160603:160008.583 In substitute_key_macros() data:'ifOperStatus[em0]'
 10255:20160603:160008.583 In activate_host() hostid:10106 itemid:24788 type:0
 10258:20160603:160008.583 End of filter_evaluate_and_or():SUCCEED
 10255:20160603:160008.583 End of activate_host()

**Comment by carlosabalde** [comment]
It looks like some Chinese character is present at the beginning of the Python script in charge of discovering items and reporting values of items (i.e. `/usr/local/bin/zabbix-varnish-cache.py`). Can you try to remove that and then execute the script manually?

![screenshot](https://cloud.githubusercontent.com/assets/342614/15772157/d55d097a-296f-11e6-871e-ce63efacf3d2.jpg)

**Comment by ekkljs** [comment]
Ok! Just recopied the file and excuted the script. 

[root@proxy bin]# /usr/local/bin/zabbix-varnish-cache.py
Traceback (most recent call last):
  File "/usr/local/bin/zabbix-varnish-cache.py", line 16, in <module>
    from argparse import ArgumentParser
ImportError: No module named argparse

Is there another file to install?

**Comment by carlosabalde** [comment]
As you can see the `ArgumentParser` Python module is not present. That's included in the Python standard library since Python 2.7. You're probably using an older version of Python. isn't it? If so, it seems a separate package is available: https://pypi.python.org/pypi/argparse. Not sure if it would work, but you can try.

**Comment by ekkljs** [comment]
Thank you! After installing ArgumentParse, it looks like there is some progress.

Please see the log in below. However data is not shown on the screen .....

 29162:20160603:171845.009 Requested [varnish.discovery[,backends]]
 29162:20160603:171845.009 In zbx_popen() command:'/usr/local/bin/zabbix-varnish-cache.py -n '' discover backends'
 29162:20160603:171845.010 End of zbx_popen():7
 29293:20160603:171845.010 zbx_popen(): executing script
 29162:20160603:171845.118 In zbx_waitpid()
 29162:20160603:171845.118 zbx_waitpid() exited, status:0
 29162:20160603:171845.119 End of zbx_waitpid():29293
 29162:20160603:171845.119 EXECUTE_STR() command:'/usr/local/bin/zabbix-varnish-cache.py -n '' discover backends' len:127 cmd_result:'{
  "data": [
    {
'
 29162:20160603:171845.119 Sending back [{
  "data": [
    {
      "{#ID}": "default\(127.0.0.1\,\,8080\)", 
      "{#NAME}": "default(127.0.0.1,,8080)"
    }
  ]
}]
 29162:20160603:171845.119 listener #3 [waiting for connection]
 29163:20160603:171845.566 In send_buffer() host:'10.0.0.90' port:10051 values:0/100
 29163:20160603:171845.566 End of send_buffer():SUCCEED
 29163:20160603:171845.566 active checks #1 [idle 1 sec]
 29159:20160603:171845.660 collector [processing data]
 29159:20160603:171845.660 In update_cpustats()
 29159:20160603:171845.660 End of update_cpustats()
 29159:20160603:171845.660 collector [idle 1 sec]
 29160:20160603:171845.834 listener #1 [processing request]
 29160:20160603:171845.834 Requested [system.uname]
 29160:20160603:171845.834 Sending back [Linux proxy.jjd 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 00:57:44 UTC 2016 x86_64]
 29160:20160603:171845.834 listener #1 [waiting for connection]
 29161:20160603:171845.947 listener #2 [processing request]
 29161:20160603:171845.947 Requested [system.cpu.intr]
 29161:20160603:171845.947 Sending back [5334343]
 29161:20160603:171845.947 listener #2 [waiting for connection]
 29162:20160603:171846.526 listener #3 [processing request]
 29162:20160603:171846.526 Requested [system.cpu.load[percpu,avg15]]
 29162:20160603:171846.526 Sending back [0.440000]
 29162:20160603:171846.526 listener #3 [waiting for connection]
 29160:20160603:171846.541 listener #1 [processing request]
 29160:20160603:171846.542 Requested [varnish.discovery[,storages]]
 29160:20160603:171846.542 In zbx_popen() command:'/usr/local/bin/zabbix-varnish-cache.py -n '' discover storages'
 29160:20160603:171846.542 End of zbx_popen():7
 29295:20160603:171846.542 zbx_popen(): executing script
 29163:20160603:171846.566 In send_buffer() host:'10.0.0.90' port:10051 values:0/100
 29163:20160603:171846.566 End of send_buffer():SUCCEED
 29163:20160603:171846.566 active checks #1 [idle 1 sec]
 29160:20160603:171846.651 In zbx_waitpid()
 29160:20160603:171846.651 zbx_waitpid() exited, status:0
 29160:20160603:171846.651 End of zbx_waitpid():29295
 29160:20160603:171846.651 EXECUTE_STR() command:'/usr/local/bin/zabbix-varnish-cache.py -n '' discover storages' len:163 cmd_result:'{
  "data": [
    {
'
 29160:20160603:171846.651 Sending back [{
  "data": [
    {
      "{#ID}": "SMA.Transient", 
      "{#NAME}": "SMA.Transient"
    }, 
    {
      "{#ID}": "SMA.s0", 
      "{#NAME}": "SMA.s0"
    }
  ]
}]
 29160:20160603:171846.651 listener #1 [waiting for connection]
 29159:20160603:171846.661 collector [processing data]
 29159:20160603:171846.661 In update_cpustats()
 29159:20160603:171846.661 End of update_cpustats()
 29159:20160603:171846.661 collector [idle 1 sec]
 29162:20160603:171847.031 listener #3 [processing request]
 29162:20160603:171847.031 Requested [system.cpu.load[percpu,avg1]]
 29162:20160603:171847.031 Sending back [0.440000]
 29162:20160603:171847.031 listener #3 [waiting for connection]
 29161:20160603:171847.435 listener #2 [processing request]
 29161:20160603:171847.435 Requested [system.uname]
 29161:20160603:171847.435 Sending back [Linux proxy.jjd 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 00:57:44 UTC 2016 x86_64]
 29161:20160603:171847.435 listener #2 [waiting for connection]
 29163:20160603:171847.567 In send_buffer() host:'10.0.0.90' port:10051 values:0/100

**Comment by carlosabalde** [comment]
Log looks ok. It seems storages and backends are now properly discovered. You should be able to see those items in the Zabbix UI. Now you should try to execute the cron jobs manually (ideally using the Zabbix user) and check output.

**Comment by ekkljs** [comment]
Good. After excuting " /usr/local/bin/zabbix-varnish-cache.py send -c /etc/zabbix/zabbix_agentd.conf -s dev > /dev/null 2>&1" command using zabbix user, there is nothing coming out. Is this normal?

**Comment by carlosabalde** [comment]
Nothing is shown in the output because you're redirecting `stdout` and `stderr` to `/dev/null`. That's ok for cron, but it's not a great idea if you want to check the output of the command ;)

**Comment by ekkljs** [comment]
Aha... Sorry for my ignorance. So what's the expression to see if it's working?

**Comment by carlosabalde** [comment]
No problem :) You simply need to execute the cronjob removing the `stdout` and `stderr` redirections.

**Comment by ekkljs** [comment]
This is output in CLI but it is still not shown on Zabbix UI.

 /usr/local/bin/zabbix-varnish-cache.py send -c /etc/zabbix/zabbix_agentd.conf
- varnish.stat["MAIN.sess_conn"] 1464952918 5234
- varnish.stat["MAIN.fetch_head"] 1464952918 0
- varnish.stat["VBE.default(127.0.0.1\,\,8080).bereq_hdrbytes"] 1464952918 4843426
- varnish.stat["MAIN.sess_dropped"] 1464952918 0
- varnish.stat["MAIN.sess_readahead"] 1464952918 8
- varnish.stat["MAIN.n_gzip"] 1464952918 0
- varnish.stat["MAIN.client_req_417"] 1464952918 0
- varnish.stat["MAIN.n_backend"] 1464952918 1
- varnish.stat["MAIN.backend_busy"] 1464952918 0
- varnish.stat["MAIN.fetch_no_thread"] 1464952918 0
- varnish.stat["MAIN.threads"] 1464952918 100
- varnish.stat["MAIN.backend_unhealthy"] 1464952918 0
- varnish.stat["MAIN.s_pipe_hdrbytes"] 1464952918 103
- varnish.stat["MAIN.sess_fail"] 1464952918 0
- varnish.stat["MAIN.s_pipe_out"] 1464952918 970
- varnish.stat["MAIN.uptime"] 1464952918 118361
- varnish.stat["MAIN.losthdr"] 1464952918 0
- varnish.stat["MAIN.bans_lurker_obj_killed"] 1464952918 0
- varnish.stat["MAIN.fetch_bad"] 1464952918 0
- varnish.stat["MAIN.fetch_304"] 1464952918 1795
- varnish.stat["MAIN.backend_conn"] 1464952918 9882
- varnish.stat["MAIN.backend_reuse"] 1464952918 0
- varnish.stat["MAIN.n_purges"] 1464952918 0
- varnish.stat["MAIN.sess_closed"] 1464952918 927
- varnish.stat["MAIN.cache_miss"] 1464952918 3490
- varnish.stat["MAIN.cache_hitpass"] 1464952918 27
- varnish.stat["MAIN.backend_req"] 1464952918 9880
- varnish.stat["MAIN.bans_obj_killed"] 1464952918 0
- varnish.stat["MGT.uptime"] 1464952918 118361
- varnish.stat["MAIN.s_pipe_in"] 1464952918 0
- varnish.stat["VBE.default(127.0.0.1\,\,8080).beresp_hdrbytes"] 1464952918 3231469
- varnish.stat["VBE.default(127.0.0.1\,\,8080).beresp_bodybytes"] 1464952918 684382221
- varnish.stat["MAIN.fetch_eof"] 1464952918 0
- varnish.stat["MAIN.fetch_failed"] 1464952918 0
- varnish.stat["MAIN.s_fetch"] 1464952918 9880
- varnish.stat["VBE.default(127.0.0.1\,\,8080).happy"] 1464952918 0
- varnish.stat["MAIN.n_lru_nuked"] 1464952918 0
- varnish.stat["MAIN.s_req"] 1464952918 10138
- varnish.stat["MAIN.n_obj_purged"] 1464952918 0
- varnish.stat["MAIN.cache_hit"] 1464952918 256
- varnish.stat["MAIN.bans"] 1464952918 1
- varnish.stat["MAIN.client_req_400"] 1464952918 0
- varnish.stat["STG.SMA.Transient.c_fail"] 1464952918 0
- varnish.stat["MAIN.s_synth"] 1464952918 0
- varnish.stat["MAIN.backend_recycle"] 1464952918 0
- varnish.stat["VBE.default(127.0.0.1\,\,8080).bereq_bodybytes"] 1464952918 20082
- varnish.stat["MAIN.backend_retry"] 1464952918 0
- varnish.stat["MAIN.busy_wakeup"] 1464952918 2
- varnish.stat["MAIN.s_resp_bodybytes"] 1464952918 637063548
- varnish.stat["VBE.default(127.0.0.1\,\,8080).pipe_in"] 1464952918 970
- varnish.stat["MAIN.threads_failed"] 1464952918 0
- varnish.stat["MAIN.s_req_hdrbytes"] 1464952918 4687329
- varnish.stat["MAIN.fetch_length"] 1464952918 7369
- varnish.stat["MAIN.esi_warnings"] 1464952918 0
- varnish.stat["STG.SMA.s0.g_space"] 1464952918 1072540541
- varnish.stat["MAIN.n_objectcore"] 1464952918 70
- varnish.stat["MAIN.s_pipe"] 1464952918 2
- varnish.stat["MAIN.threads_created"] 1464952918 100
- varnish.stat["MAIN.n_objecthead"] 1464952918 72
- varnish.stat["MAIN.s_resp_hdrbytes"] 1464952918 3977060
- varnish.stat["MAIN.s_req_bodybytes"] 1464952918 20082
- varnish.stat["MAIN.threads_destroyed"] 1464952918 0
- varnish.stat["STG.SMA.s0.g_bytes"] 1464952918 1201283
- varnish.stat["MAIN.thread_queue_len"] 1464952918 0
- varnish.stat["MAIN.fetch_204"] 1464952918 0
- varnish.stat["MAIN.client_req"] 1464952918 10138
- varnish.stat["MAIN.sess_drop"] 1464952918 0
- varnish.stat["VBE.default(127.0.0.1\,\,8080).pipe_hdrbytes"] 1464952918 248
- varnish.stat["MAIN.fetch_chunked"] 1464952918 714
- varnish.stat["STG.SMA.Transient.g_bytes"] 1464952918 0
- varnish.stat["MAIN.sess_queued"] 1464952918 0
- varnish.stat["MAIN.s_pass"] 1464952918 6390
- varnish.stat["MAIN.n_expired"] 1464952918 3425
- varnish.stat["MAIN.n_object"] 1464952918 65
- varnish.stat["MAIN.fetch_1xx"] 1464952918 0
- varnish.stat["STG.SMA.Transient.g_space"] 1464952918 0
- varnish.stat["MAIN.n_gunzip"] 1464952918 353
- varnish.stat["MAIN.busy_sleep"] 1464952918 2
- varnish.stat["MAIN.esi_errors"] 1464952918 0
- varnish.stat["VBE.default(127.0.0.1\,\,8080).pipe_out"] 1464952918 0
- varnish.stat["MAIN.s_sess"] 1464952918 5234
- varnish.stat["MAIN.threads_limited"] 1464952918 0
- varnish.stat["MAIN.backend_fail"] 1464952918 0
- varnish.stat["STG.SMA.s0.c_fail"] 1464952918 0

**Comment by carlosabalde** [comment]
The output looks good, but I miss the last part (a summary with number of items processed, failed, etc.). I also miss the `-s` option when executing `zabbix-varnish-cache.py`. If not present Zabbix Server is not going to be able to match with a host the submitted items.

**Comment by ekkljs** [comment]
Thank you! Should I use "/usr/local/bin/zabbix-varnish-cache.py send -c /etc/zabbix/zabbix_agentd.conf" instead of "/usr/local/bin/zabbix-varnish-cache.py send -c /etc/zabbix/zabbix_agentd.conf -s dev > /dev/null 2>&1" as cron job? If I use "/usr/local/bin/zabbix-varnish-cache.py send -c /etc/zabbix/zabbix_agentd.conf -s dev > /dev/null 2>&1", it is not updated on Zabbix UI. If I use "/usr/local/bin/zabbix-varnish-cache.py send -c /etc/zabbix/zabbix_agentd.conf" it is updated on Zabbix UI.

**Comment by carlosabalde** [comment]
The `-s` option is used to provide the host name as registered in the Zabbix Server UI. I'm not sure about the behaviour of Zabbix Sender when that option is not provided. I guess it will use the current hostname or something defined in the configuration of Zabbix Agent when submitting values of items to Zabbix Server.

**Comment by ekkljs** [comment]
Ok. Thanks for helping!!

**Comment by ekkljs** [comment]
I don' think I mentioned this is a great code to help my job. Thank you again.
