### ISSUE TITLE
Which location did i define for {$VARNISH_CACHE.LOCATIONS}

### ISSUE THREAD

**Issue by cihatturan** [allenta/zabbix-template-for-varnish-cache#50]
I want to monitor, discovery rules but, when i try to give {$VARNISH_CACHE.LOCATIONS} => /var/lib/varnish/; Zabbix already says "Unsupported Item key" for Discovery rules. Which location did i define for this macro.

Thanks for your help.

**Comment by carlosabalde** [comment]
On the one hand, `{$VARNISH_CACHE.LOCATIONS}` macro is a comma-delimited list of Varnish Cache Plus instance names. Usually you should leave its value blank when running a single instance per server.

On the other hand, 'unsupported item key' errors usually mean user parameters in Varnish Agent have not been properly configured.
