### ISSUE TITLE
had to change -s dev to -s $HOSTNAME

### ISSUE THREAD

**Issue by Jefl** [allenta/zabbix-template-for-varnish-cache#7]
Hi,
I had to change the cron job from -s dev to -s $HOSTNAME for it to work properly.
Is this a but or just something not specified in the readme ?

Cheers,

Jef

**Comment by carlosabalde** [comment]
That's something referenced in the README.md file ('... beware of the -i and -s optins...') and documented when executing the script with the --help option. But yes, it could be much better documented :)
