### ISSUE TITLE
"Invalid" JSON

### ISSUE THREAD

**Issue by antonpm1** [allenta/zabbix-template-for-varnish-cache#8]
Hi Guys,

Really liking the look of this project. I've made the fix outlined in https://github.com/allenta/zabbix-template-for-varnish-cache/issues/6 and the script is returning nicely.

I noticed I'm getting:

`info from server: "processed: 0; failed: 89; total: 89; seconds spent: 0.000542"
sent: 89; skipped: 0; total: 89`

Running the command as:

`/usr/local/bin/zabbix-varnish-cache.py -i '' send -c /etc/zabbix/zabbix_agentd.conf -s `hostname``

The Zabbix (3.0) Front-end says the value needs to be valid JSON. I put the server into debug and captured what the host was sending and the output looks fine in a JSON validator.

This is the user params entry:

`[root@cache-01 ~]$ cat /etc/zabbix/zabbix_agentd.d/userparameter_varnish.conf 
UserParameter=varnish.discovery[*],/usr/local/bin/zabbix-varnish-cache.py -i '$1' discover $2`

The only thing I'm not too sure on is the $VARNISH_CACHE_LOCATIONS macro. I saw the host has inherited this macro from the template and it doesn't have a value, but the instructions say this should be blank if there is only one Instance running on the server. Does this mean to just leave it without a value?

Thanks,

Anton

**Comment by carlosabalde** [comment]
Hi,

I running a single `varnishd` instance per server (which is the most common scenario), you don't need to worry about the `$VARNISH_CACHE_LOCATIONS` macro. Leaving it blank in the right thing to do.

**Comment by carlosabalde** [comment]
I'd suggest executing the Python script using the Zabbix user. The invalid JSON output message is usually related with errors dumped by the script when executed by Zabbix (no permissions to access to VSL, etc.).

**Comment by antonpm1** [comment]
Thanks for the quick reply. I have made that change now and confirmed that it will run as Zabbix. I will check this one again tomorrow when the host comes out of maintenance (I don't think it will try to re-run the auto discovery if not data is set to be collected).

**Comment by antonpm1** [comment]
Hi,

Thanks, your suggestion was absolutely correct - feel a bit bad that I didn't get it myself!

I'll close this one off now.

Thanks again,

Anton
